<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionNumber Condition="'$(VersionNumber)' == '' ">24.9</VersionNumber>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	    <Version>$(VersionNumber)</Version>
    <PackAsTool>False</PackAsTool>
    <DelaySign>False</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
